### ISSUE TITLE
Configurar https

### ISSUE THREAD

**Issue by ccamara** [qgises/qgis-es#11]
Configurar certificado https autorenovado a través de let's encrypt.

Depende de #10

**Comment by msevilla00** [comment]
@ccamara, @carlospsig ya cambió el dominio, #10, y las imágenes no se carga aún #36 debido a este issue.

**Comment by ccamara** [comment]
El problema es que en la issue #10 había que hacer dos cambios en los registros del dominio (uno para www.gis.es y otro para qgis.es) y solo se ha hecho uno. Al faltar el de qgis.es no funciona el https y por eso no se ven las imágenes de fondo (#36) y no puedo hacer esto.

**Comment by ccamara** [comment]
¡Hecho!
