### ISSUE TITLE
Corregir formulario de alta de socios

### ISSUE THREAD

**Issue by ccamara** [qgises/qgis-es#213]
Al acceder al [formulario de alta de socios](https://www.qgis.es/alta-socios/) aparece un mensaje diciendo que el formulario de typeform ha cambiado:

![image](https://user-images.githubusercontent.com/706549/162207054-79e4dbf7-7386-4987-bd09-fd583661265e.png)

Habría que editar esta línea para añadir el nuevo ID del formulario (que desconozco y por eso no puedo hacer el PR) y reflejar el cambio:

https://github.com/qgises/qgis-es/blob/8bc29bce70e9879304c2da23801c8e221620acfb/content/alta-socios.md?plain=1#L18

**Comment by msevilla00** [comment]
Se migró el sistema a un formulario propio y se incluyó enlace en la web.
