### ISSUE TITLE
Problemas en la carga de imágenes de fondo

### ISSUE THREAD

**Issue by msevilla00** [qgises/qgis-es#36]
La imágenes de fondo de las páginas principales (e.g. asociación) no se cargan.

**Comment by ccamara** [comment]
Efectivamente, ahora no se muestran las imágenes, pero se solucionará solo cuando esté cerrada la issue #10 . Me explico:

Ahora mismo tengo configurado netlify para que use como dominio principal qgis.es , para que cuando quien gestiona el dominio (@carlospsig ?) apunte a nuestro repo, ya se vea la web que hay en este repo en lugar de la anterior. 

El problema está en que ahora, las imágenes de fondo las busca en qgis.es/, y como no existen aún, no las encuentra.

**Comment by ccamara** [comment]
El commit 0b06985ccb8251c284c34902000e9fbf1e5c20c8 es una solución rápida y temporal para esto. En cuanto esté hecha la issue #10  y pueda terminar la #11, restauraré la configuración inicial y esta tarea estará resuelta definitivamente.

**Comment by msevilla00** [comment]
La imagen de fondo de https://www.qgis.es/asociacion/ no se ve, no se si es por esa última revisión. Pensé que era por el tamaño de la imagen he hice último commit.

**Comment by ccamara** [comment]
El problema de esa imagen era que tenía una opacidad del 100% y por eso no se veía y se veía todo negro. El commit ff16238 cambia la opacidad a un 40% (variable `image_darken = 0.4 `), que es como si tuviese un fondo negro encima al 40%.

Cierro la issue, porque se ven todas las imágenes de fondo de portada y de la asociación correctamente.
