### ISSUE TITLE
Revisar TODO el contenido de la página web

### ISSUE THREAD

**Issue by msevilla00** [qgises/qgis-es#37]
Antes del cambio del dominio debemos revisar integramente todo el contenido de la web.

**Comment by lefcgis** [comment]
Actualicé mis datos, lo guardé, pero sigue sin actualizarse en la web, @msevilla00 

L.

**Comment by lefcgis** [comment]
He revisado la web y hay algunas cosas que reajustar. Aún no tengo muy claro en el _how_ pero seguro y me orientais internamente en algunos aspectos técnicos :D

**Comment by clds1** [comment]
He revisado la web y he abierto algunos issues con enlaces que faltan o reajustes en los contenidos.
Muy buen trabajo chicos!!! Sois unos cracks!!!
Bss

**Comment by msevilla00** [comment]
A la vista de que hoy se ha hecho pública la nueva web y que creo que menejamos mejor cada errata en issues independientes cierro este. Para más cuestiones abrid issue particular. Saludos

**Comment by clds1** [comment]
Me parece perfecto @msevilla00 !! Gracias por todo el trabajo que estás haciendo con las gestiones de la web!! Enhorabuena. Bss
