### ISSUE TITLE
Cambiar correo de notificación de errores en netlify

### ISSUE THREAD

**Issue by msevilla00** [qgises/qgis-es#40]
Cambiar el correo para notificar fallos en netlify que ahora está apuntando al correo de Carlos Cámara.
Se gestiona en: https://app.netlify.com/sites/qgises/settings/deploys

**Comment by msevilla00** [comment]
@carlospsig @guspresa @clds1 he añadido mi correo y el de info@qgis.es para notificaciones de problemas en los "deploys" de netlify. Cierro Issue.

**Comment by clds1** [comment]
BIEN!!

*Carmen Díez* <http://www.linkedin.com/in/carmen-diez-sanmartin-5a33924b>
*@carmen10maica* <https://twitter.com/carmen10maica>
