### ISSUE TITLE
Falta enlace en el apartado de Haz una donación

### ISSUE THREAD

**Issue by sigdeletras** [qgises/qgis-es#56]
Hola

Creo q es el único enlace que falta y éste es importante 😀

Felicidades por la web

![Screenshot_20201016-181811](https://user-images.githubusercontent.com/4746157/96285028-ae846280-0fde-11eb-8cb3-8b87b7a5fe99.png)

**Comment by clds1** [comment]
@msevilla00 
el número de cuenta de la asociación y el enlace de paypal están en drive en el siguiente documento (compartido con la junta directiva exclusivamente):

https://docs.google.com/document/d/15OF55zskx3G7S5w6uTZV2LawED9ngIiBnIxWWHrlnAk/edit?usp=sharing

para ponerlo en el apartado de donaciones.
