### ISSUE TITLE
Subtítulo para apartado Eventos

### ISSUE THREAD

**Issue by sigdeletras** [qgises/qgis-es#57]
Siguiendo la línea de diseño fatla un subtñitulo para el apartado Eventos al igual que está en Blog o en Contáctanos

![image](https://user-images.githubusercontent.com/4746157/96286140-3880fb00-0fe0-11eb-848a-82f2b17ffcd0.png)

**Comment by msevilla00** [comment]
He añadido: Reuniones, talleres, conferencias y otras actividades. Gracias @sigdeletras !
