### ISSUE TITLE
Enlace a las actas de la asamblea general

### ISSUE THREAD

**Issue by clds1** [qgises/qgis-es#58]
Hay que cambiar el enlace al acta de la Asamblea General que está en drive:

https://docs.google.com/document/d/1IaPlSoIbQmQ8lx31IFAiIHeVVTqMcAeT-EsZfxvAOT4/edit?usp=sharing

**Comment by msevilla00** [comment]
Puse enlace a descarga en PDF:
https://docs.google.com/document/d/1IaPlSoIbQmQ8lx31IFAiIHeVVTqMcAeT-EsZfxvAOT4/export?format=pdf

**Comment by clds1** [comment]
Genial!!
