### ISSUE TITLE
Incluir logo y enlace a socios colectivos, grandes y pequeños

### ISSUE THREAD

**Issue by clds1** [qgises/qgis-es#59]
@All4Gis @msevilla00 

Ahora mismo aparecen en la web sólo dos grandes colectivos: Ajuntament de Barcelona y Asociación española de QGIS.

Yo incluiría todos los colectivos, aunque sea en dos niveles (unos en grande al principio, y los otros más abajo en caracteres más pequeños), pero es un buen reclamo. Yo pondría el logo y en enlace a su página web.
A día de hoy han pagado la cuota del 2020:
Gran colectivo: Ayuntamiento de Barcelona (https://cibernarium.barcelonactiva.cat/) y GISWATER (https://www.giswater.org/)
Pequeño colectivo: FISOTEC (https://fisotec.es/), PANOimagen (https://www.panoimagen.com/) y GEOINNOVA (https://geoinnova.org/)

Si necesitáis los logos, se les puede pedir a los socios, aunque estarán en sus web y en nuestro drive también hay algunos.

**Comment by msevilla00** [comment]
He puesto en el apartado cómo "en construcción" y queda pendiente de añadir cada uno de ellos a través de una ficha por cada socio/colectivo (una ficha de tipo *author*).

**Comment by sigdeletras** [comment]
Me adelanto, y no creo que Luis Quesada me diga lo contrario, pero contad con Geoinnova para lo que necesitéis.

**Comment by msevilla00** [comment]
Magnifico! Habrá que tener listo un perfil de "author" en la página.

Para ello puedes ver el modelo en cualquiera de las otras entradas de la junta o el ayuntamiento de Barcelona (que ahora que veo hay que actualizar) o mejor, el de CArlos, por ejemplo:

- [https://github.com/qgises/qgis-es/tree/master/content/authors/carlospsig](https://github.com/qgises/qgis-es/tree/master/content/authors/carlospsig).

También hay instrucciones en el manual de la página web al respecto:

- [https://www.qgis.es/manuales/manual_web/contenido-tipos/#personas-y-entidades-authors](https://www.qgis.es/manuales/manual_web/contenido-tipos/#personas-y-entidades-authors)

Básicamente es preparar un directorio específico, incluir el `_index.md` de forma adecuada e incluir el logotipo/imagen como `avatar.png` o `.jpg`

**Comment by msevilla00** [comment]
Incluidos los colectivos grandes y pequeños socios en este momento.
