### ISSUE TITLE
Corregir espacio de Grandes Colectivos en la pestaña de Asociación

### ISSUE THREAD

**Issue by clds1** [qgises/qgis-es#60]
@msevilla00 @All4Gis 
En el apartado de Grandes colectivos, los enlaces de los logos de QGISes y Ayuntament de Barcelona, te llevan a un texto genérico de QGIS, que además hace referencia a QGIS Italia, lo que no tiene sentido.

https://www.qgis.es/asociacion/
https://www.qgis.es/author/socio-gran-colectivo/

Yo dejaría el texto corregido para el logo de la Asociación y actualizaría con los logos de todos los colectivos y sus enlaces directamente a sus webs.

**Comment by msevilla00** [comment]
Se relaciona con #59
