### ISSUE TITLE
Contenido en la explicación de cómo hacerse socio colectivo

### ISSUE THREAD

**Issue by clds1** [qgises/qgis-es#61]
@All4Gis @msevilla00 
https://www.qgis.es/asociacion/
¿Quieres aparecer en esta lista? Aquí te explicamos cómo.

Este comentario no tiene enlace a nada y habría que hacer un texto explicando como hacerse socio de pequeño o gran colectivo, y poner un enlace al formulario de inscripción de socios (o mejor a la pestaña correspondiente de Inscríbete que hay en la propia web).

Ejemplo de texto:
'Si tu entidad quiere colaborar con la Asociación QGIS España y participar en sus proyectos de difusión, investigación, iniciativas, patrocinio y fomento de QGIS, sólo tienes que hacerte socio inscribiéndote en el formulario y abonando la cuota correspondiente. Además, de esta manera vuestro logo también aparecerá en este espacio reservado de nuestra web para todos los colaboradores con la Asociación'

**Comment by msevilla00** [comment]
He incluido el texto y cierro al estar en relación con #59
