### ISSUE TITLE
Incluir compra del libro de SIG de V. Olaya

### ISSUE THREAD

**Issue by msevilla00** [qgises/qgis-es#62]
Parte de la venta del libro de SIG de Víctor Olaya será donada a la asociación QGIS España por lo que debemos incluirlo de alguna manera en la web. Necesitamos imagen, enlace y pensar adecuadamente en el texto.

**Comment by clds1** [comment]
Cierto! Intentaré hablar con Víctor en cuanto pueda para concretar imágen y texto.

**Comment by carlospsig** [comment]
la url de Lulu es esta:
"Sistemas de Información Geográfica"
Por:  Victor Olaya Ferrero

https://www.lulu.com/es/es/shop/victor-olaya-ferrero/sistemas-de-informaci%C3%B3n-geogr%C3%A1fica/hardcover/product-76em9n.html

**Comment by msevilla00** [comment]
Podríamos hacer una entrada en el blog y ademaś incluirlo en el apartado de la asociación como un elemento "publicitario" pues al fin y al cabo sacamos dinero con ello. Podemos cortar y copiar una crítica muy buena al libro que hay en googdreads XD

**Comment by clds1** [comment]
Le he pedido a Víctor un textito para ponerlo en la web anunciando lo de su
libro. No quiere poner ninguna foto suya, sólo en enlace al libro.

Me parece bien ponerlo en un apartado concreto fijo, sólo en el blog me
parece poco, aunque hagamos referencia a él cuando lo consideremos.

Se podría abrir un apartado de 'colaboraciones con la asociación', o algo
así, y poner ahí enlaces a este tipo de cosas.

¿qué os parece?

En cuanto me pase Víctor el texto lo incluyo.

Bss

*Carmen Díez* <http://www.linkedin.com/in/carmen-diez-sanmartin-5a33924b>
*@carmen10maica* <https://twitter.com/carmen10maica>

**Comment by lefcgis** [comment]
hola. Lamento la demora. Tenía ya elaborado un flyer sencillo. No sé [qué les parece](https://github.com/lefcgis/Libertad/blob/master/SIG.png). Tal vez y lo complemento con información que brinde Víctor

**Comment by msevilla00** [comment]
Cierro el issue que ya lleva tiempo resuelto con enlace en la barra superior/menú y entrada en el blog.
